// <auto-generated />
using System;
using CargoTrack.Modules.Logistics.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CargoTrack.Modules.Logistics.Database.Migrations
{
    [DbContext(typeof(LogisticsDbContext))]
    [Migration("20260228162557_AddCargoTypeRelationToJobOffers")]
    partial class AddCargoTypeRelationToJobOffers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("logistics")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CargoTrack.Modules.Logistics.Entities.CargoType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredTrailer")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CargoTypes", "logistics");
                });

            modelBuilder.Entity("CargoTrack.Modules.Logistics.Entities.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(Point, 4326)");

                    b.Property<Guid>("NpcCompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NpcCompanyId");

                    b.ToTable("Depots", "logistics");
                });

            modelBuilder.Entity("CargoTrack.Modules.Logistics.Entities.JobOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CargoName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CargoTypeId")
                        .HasColumnType("uuid");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("boolean");

                    b.Property<int>("RequiredTrailer")
                        .HasColumnType("integer");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SourceDepotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetDepotId")
                        .HasColumnType("uuid");

                    b.Property<double>("WeightTons")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CargoTypeId");

                    b.HasIndex("SourceDepotId");

                    b.HasIndex("TargetDepotId");

                    b.ToTable("JobOffers", "logistics");
                });

            modelBuilder.Entity("CargoTrack.Modules.Logistics.Entities.NpcCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("NpcCompanies", "logistics");
                });

            modelBuilder.Entity("CargoTrack.Modules.Logistics.Entities.Depot", b =>
                {
                    b.HasOne("CargoTrack.Modules.Logistics.Entities.NpcCompany", "NpcCompany")
                        .WithMany()
                        .HasForeignKey("NpcCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpcCompany");
                });

            modelBuilder.Entity("CargoTrack.Modules.Logistics.Entities.JobOffer", b =>
                {
                    b.HasOne("CargoTrack.Modules.Logistics.Entities.CargoType", "CargoType")
                        .WithMany()
                        .HasForeignKey("CargoTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CargoTrack.Modules.Logistics.Entities.Depot", "SourceDepot")
                        .WithMany()
                        .HasForeignKey("SourceDepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CargoTrack.Modules.Logistics.Entities.Depot", "TargetDepot")
                        .WithMany()
                        .HasForeignKey("TargetDepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoType");

                    b.Navigation("SourceDepot");

                    b.Navigation("TargetDepot");
                });
#pragma warning restore 612, 618
        }
    }
}
