// <auto-generated />
using System;
using CargoTrack.Modules.Transport.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CargoTrack.Modules.Transport.Database.Migrations
{
    [DbContext(typeof(TransportDbContext))]
    [Migration("20260208164652_InitTransport")]
    partial class InitTransport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("transport")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CargoTrack.Modules.Transport.Entities.TransportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Point>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("geography(Point, 4326)");

                    b.Property<DateTime>("EstimatedArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<LineString>("RouteGeometry")
                        .IsRequired()
                        .HasColumnType("geography(LineString, 4326)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TotalDistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TruckId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Transports", "transport");
                });
#pragma warning restore 612, 618
        }
    }
}
