// <auto-generated />
using System;
using CargoTrack.Modules.Transport.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CargoTrack.Modules.Transport.Database.Migrations
{
    [DbContext(typeof(TransportDbContext))]
    [Migration("20260217163943_AddCompanyRelations")]
    partial class AddCompanyRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CargoTrack.Modules.Transport.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Reputation")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Companies", "game");
                });

            modelBuilder.Entity("CargoTrack.Modules.Transport.Entities.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedTruckId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDriving")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTruckId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Drivers", "game");
                });

            modelBuilder.Entity("CargoTrack.Modules.Transport.Entities.Garage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(Point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Slots")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Garages", "game");
                });

            modelBuilder.Entity("CargoTrack.Modules.Transport.Entities.Trailer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttachedTruckId")
                        .HasColumnType("uuid");

                    b.Property<double>("CargoCapacityKg")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<double>("Condition")
                        .HasColumnType("double precision");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttachedTruckId")
                        .IsUnique();

                    b.HasIndex("CompanyId");

                    b.HasIndex("GarageId");

                    b.ToTable("Trailers", "game");
                });

            modelBuilder.Entity("CargoTrack.Modules.Transport.Entities.TransportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Point>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("geography(Point, 4326)");

                    b.Property<DateTime>("EstimatedArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<LineString>("RouteGeometry")
                        .IsRequired()
                        .HasColumnType("geography(LineString, 4326)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TotalDistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<Guid>("TruckId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ActiveTransports", "transport");
                });

            modelBuilder.Entity("CargoTrack.Modules.Transport.Entities.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Condition")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Fuel")
                        .HasColumnType("numeric");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDriving")
                        .HasColumnType("boolean");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxFuel")
                        .HasColumnType("numeric");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Odometer")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductionYear")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("GarageId");

                    b.ToTable("Trucks", "game");
                });

            modelBuilder.Entity("CargoTrack.Modules.Transport.Entities.Driver", b =>
                {
                    b.HasOne("CargoTrack.Modules.Transport.Entities.Truck", null)
                        .WithMany()
                        .HasForeignKey("AssignedTruckId");

                    b.HasOne("CargoTrack.Modules.Transport.Entities.Company", "Company")
                        .WithMany("Drivers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CargoTrack.Modules.Transport.Entities.Trailer", b =>
                {
                    b.HasOne("CargoTrack.Modules.Transport.Entities.Truck", "AttachedTruck")
                        .WithOne("CurrentTrailer")
                        .HasForeignKey("CargoTrack.Modules.Transport.Entities.Trailer", "AttachedTruckId");

                    b.HasOne("CargoTrack.Modules.Transport.Entities.Company", "Company")
                        .WithMany("Trailers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CargoTrack.Modules.Transport.Entities.Garage", null)
                        .WithMany("Trailers")
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttachedTruck");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CargoTrack.Modules.Transport.Entities.Truck", b =>
                {
                    b.HasOne("CargoTrack.Modules.Transport.Entities.Company", "Company")
                        .WithMany("Trucks")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CargoTrack.Modules.Transport.Entities.Garage", null)
                        .WithMany("Trucks")
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CargoTrack.Modules.Transport.Entities.Company", b =>
                {
                    b.Navigation("Drivers");

                    b.Navigation("Trailers");

                    b.Navigation("Trucks");
                });

            modelBuilder.Entity("CargoTrack.Modules.Transport.Entities.Garage", b =>
                {
                    b.Navigation("Trailers");

                    b.Navigation("Trucks");
                });

            modelBuilder.Entity("CargoTrack.Modules.Transport.Entities.Truck", b =>
                {
                    b.Navigation("CurrentTrailer");
                });
#pragma warning restore 612, 618
        }
    }
}
